### ISSUE TITLE
save button broken

### ISSUE THREAD

**Issue by stchang** [racketscript/racketscript-playground#22]
specifically, `assoc->object` errors

maybe related to https://github.com/vishesh/racketscript-playground/issues/5

**Comment by vishesh** [comment]
Yes, Github deprecated anonymous gists and we didn't support Github logins. https://github.blog/2018-02-18-deprecation-notice-removing-anonymous-gist-creation/

**Comment by stchang** [comment]
Yah, I'm looking at this now. Just opening an issue to keep track :)

**Comment by stchang** [comment]
Do you think the easiest first step is to just associate an account with the app?

**Comment by vishesh** [comment]
Yes, I think first step would be to add a button to login using Github oauth with access to Gists. https://docs.github.com/en/developers/apps/building-oauth-apps

**Comment by stchang** [comment]
is that the same as the "login with github" that you see on other sites?

**Comment by vishesh** [comment]
Yes. Because, that's the only way to get a token IMO.

**Comment by stchang** [comment]
I'm almost definitely doing something wrong, but I think I'm getting blocked by CORS policy again.

considering two possible next steps:
- use "gatekeeper" https://stackoverflow.com/questions/42150075/cors-issue-on-github-oauth/42150336
- or go with "non-web app flow" https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps

Do you know anything about this issue?

**Comment by vishesh** [comment]
Umm, sorry, no idea about that. :(

**Comment by stchang** [comment]
Hah, it's fine. I'll keep trying

**Comment by stchang** [comment]
fixed https://github.com/racketscript/racketscript-playground/pull/25
