### ISSUE TITLE
Use github account to save and load scripts

### ISSUE THREAD

**Issue by vishesh** [racketscript/racketscript-playground#5]
We use anonymous gist at the moment, but linking those gist with account and being able to update them when logged in is really useful. Users can keep track of their programs, and maybe we could too!

**Comment by vityou** [comment]
It Would also be useful if you could open and save files to your google drive account.  This would be useful for doing htdp exercises.  Also, I'm not sure if this is possible, but it would be useful to be able to install packages.

**Comment by vishesh** [comment]
@vityou Thank you. Its a good suggestion.

**Comment by stchang** [comment]
done https://github.com/racketscript/racketscript-playground/pull/25
